// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfukigjwkrefrlricsgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdWtpZ2p3a3JlZnJscmljc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzI2MjUsImV4cCI6MjA3Mzk0ODYyNX0.FBZ-D7guh7faZwGtSQCAj6AEmDsVhrK79-RPn0R0s4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});